### ISSUE TITLE
Negative cache breaks tier model

### ISSUE THREAD

**Issue by kf6kjg** [kf6kjg/WHIP-LRU#2]
Consider three WHIP-LRU servers: 1, 2, 3.  1 and 2 have server 3 has their upstream server, creating a tree with 3 as the root, 1 and 2 as leaves.

If a given asset ID is requested from 1, but neither 1 nor 3 recognize the asset, both will then place it into their negative cache.  If the same ID is put into server 2, both 2 and 3 will store the asset and 3 will clear it from its negative cache.  However, server 1 WILL STILL have that ID in its negative cache causing the servers to be inconsistent with each other.

Thankfully this should, in theory, be a rare occurrence, and will only affect tiered WHIP-LRU installations - of which there are none at this time.

**Comment by appurist** [comment]
First, this is only an issue in the case of using multiple WHIP-LRU servers a hierarchical architecture. And in those cases, the downstream servers should have a very short timeout on the negative cache (e.g. something like 5-30 seconds).  

I think this would not be as rare an occurrence as it seems, since it may be common to upload something and send it to someone on another region with a different asset server, or to upload something and teleport to that other server.

I think it's important for the negative cache to be implement to handle the case of a poorly-implemented script or viewer causing a flood of repeated requests, but that even a small negative cache timeout would take care of that.

It's also possible for the upstream asset server to have a very long negative cache timeout, since it should be the authoritative source for all new assets.  However, that is likely not the case initially, with a hybrid mix of test regions funneling requests through WHIP-LRU but others going directly to Cloud Files.  So initially a small negative cache timeout could be used on the upstream LRU asset server as well, then a much longer one once all regions were using it.

**Comment by kf6kjg** [comment]
I agree about short time limits helping alleviate the issue. So I see the following actionable ideas:
1. Temporally limiting the negative cache.
2. Making the time limit configurable.

The case you mentioned in your second paragraph is I think a different situation, and one that never hits the negative cache: an asset is put into server 1, which then caches it and forwards it to server 3, which in turn caches it.  Then a get for that UUID happens on server 2, which doesn't recognize it, so asks server 3.  Server 3 responds with the asset, server 2 then caches the asset and send it on to the requester.

**Comment by appurist** [comment]
That sounds like a plan, except for the last bit. Are you saying that any upload is relayed to all sibling peers? That seems like something that is more complex than it is worth for this case.  Or the upper level notifies all child servers? Again, not worth it if a short negative cache takes care of that. Negative cache timeout == forced refresh of data, which would pick it up.

**Comment by kf6kjg** [comment]
WHIP-LRU servers only know about upstream servers, and that at only one level up. Methinks I need to sketch the configuration being considered in this issue...

**Comment by kf6kjg** [comment]
Ok, the last two commits hit the two action points I mentioned above, thus probably resolving this issue.

I do have a question: should a hit on the negative cache update the expiration of the item, or should it just expire?  I'm leaning towards the latter as it will help resolve this problem better - and is how it's currently coded.

I should probably support disabling the negative cache too, but that can be another issue.

**Comment by appurist** [comment]
It's good that a hit does not update the negative cache. Since the negative cache isn't part of the LRU list, a hit should only do an update when acting on the positive cache hit.  It's just an attempt to decrease the number of more complex tests, a performance improvement, with a short false-negative time for a new item being created that may be caused by the negative cache. So as long as it is very short, and does not apply to the region where a new asset is created, it needs to get refreshed after the short negative cache timeout, regardless of how many hits there have been in between.

**Comment by kf6kjg** [comment]
With the recent addition of being able to disable the negative cache, along with a note in the sample INI, I think this problem can be resolved.
